### PR TITLE
Add 2.4GHz and 5GHz metrics

### PR DESCRIPTION
**Pull request by tux-84**
2.4GHz and 5GHz metrics were missing

### CODE REVIEW

**Comment by xperimental** [comment]
Hi @jzielke84, thanks for the contribution and sorry for the long delay...

I finally managed to look at your PR, but unfortunately the statistics of my local Freifunk community do not include the client type. Could you point me to a community where the statistics are available?

**Comment by tux-84** [comment]
@xperimental Sorry for the late reponse. Sure we from COlogne/Bonn (ffkbu) use those: https://map.kbu.freifunk.net/#!/de/map

It's running in the dashboard I have created: https://grafana.kbu.freifunk.net/

**Comment by xperimental** [comment]
Thanks for the link, I found some `meshviewer.json` files in there that were useful.

It looks to me like the `clients` number _should_ be a total of the other three available numbers (2.4GHz, 5GHz, "other"). While this does not add up _all the time_, I would propose to have one client metric with an additional label instead of the current three your PR contains. That label could have the four values `wifi24`, `wifi5`, `other` and `unknown`, for example, with "unknown" taking the remainder of the clients in case the both wifi numbers and other do not add up or in case the information is not provided (like with my Freifunk community). This would make Prometheus' aggregation functions (sum, avg, min, max, ...) useful with the client metric in the usual "Prometheus way".

Does that sound like a good idea?

**Comment by tux-84** [comment]
Yes this makes sense.

**Comment by xperimental** [comment]
> Yes this makes sense.

Great :slightly_smiling_face: 

Do you want to do this change to your PR or should I take it over?

**Comment by tux-84** [comment]
Please take this over. I’m currently doing so much Freifunk stuff for public services like refugee camps which takes up much of my spare time already. 

Another change which I haven’t made pull request for is adding the nodes hostname to each metric where often there only would be the node‘s id. This drastically reduces query time and improves PromQL performance since I don’t have to do a join  operation on each node when parsing certain large datasets.

**Comment by xperimental** [comment]
@jzielke84 Finally got around to working on this. Have a look...

**Comment by tux-84** [comment]
Nice, thanks! One thing I would recommend you to also add is the node.Hostname label to every metric. Otherwise you need to do a PromQL join operation for every clientCount metric if you want to filter by node names in Grafana. This will result in heavy cpu load due to complex query mechanisms, especially over large datasets with a great timerange. I have modified it like this (but there is probably a more elegant way to do this, sorry, I'm a DevOp, not a developer ;-)):

```go
func (c *collector) updateNodes(ch chan<- prometheus.Metric, nodes []info.Node) {
        for _, node := range nodes {
                if node.IsGateway {
                        // skip nodes that are not routers
                        continue
                }

                metaLabels := []string{node.ID, node.Hostname, node.Model, node.Firmware.Release, node.SiteCode, node.Contact, node.Uptime, node.FirstSeen, node.LastSeen}
                sendMetric(ch, metaDesc, 1.0, metaLabels)

                idLabel := []string{node.ID}
                idAndHostLabel := []string{node.ID, node.Hostname}
                sendMetric(ch, clientCountDesc, float64(node.Clients), idLabel)
                sendMetric(ch, client24CountDesc, float64(node.ClientsWifi24), idAndHostLabel)
                sendMetric(ch, client5CountDesc, float64(node.ClientsWifi5), idAndHostLabel)
                sendMetric(ch, loadAvgDesc, node.LoadAvg, idLabel)
                sendMetric(ch, rootFsUsageDesc, node.RootfsUsage, idLabel)

                if node.MemoryUsage > 0 {
                        sendMetric(ch, memoryUsageDesc, node.MemoryUsage, idLabel)
                }
        }
}
```

**Comment by xperimental** [comment]
@jzielke84 The router meta information used to be on the "client count" metric in the early versions of the exporter. This was changed once there were more metrics for each router. The timerange for the query should not be a major factor for the join unless you have a lot of churn (routers joining and leaving your network). How large is your dataset?

---

Did you try out the updated version of your PR with your dataset already? I'd go forward and merge this PR if there's no issue with this change.

**Comment by tux-84** [comment]
@xperimental We use it to generate the listing of our Top-X Nodes serving the most clients and for firmware overview. This would require a join between the node's name filter and the node's id to get the firmware information.

**Comment by xperimental** [comment]
Yes, that kind of query currently requires something that would be a JOIN in SQL. My point was that this should not cause a large impact on query performance (yes, there is a non-zero impact, but it should be negligible) at least with the datasets I would expect from this exporter.

---

Also, this is not really relevant to _this_ PR's discussion. We can keep talking about this in a separate issue, but for now I'd like to limit the discussion here to what's relevant to the PR.

Can you please test with the updated code from the PR if you did not do that already and give me some feedback on that?

**Comment by tux-84** [comment]
@xperimental Sorry for the late response. I was too busy and forgot about this one.

Edit: Hm, the patch has been applied, the exporters start fine but somehow the metics for 5GHz and 2.4Gz Clients don't show up in the output.

Example:

Datasource: https://map.kbu.freifunk.net/data/ffkbub-V2/meshviewer.json

```shell
# curl -s http://10.0.1.1:9252/metrics | grep freifunk_router_client_count_total | grep [1-9]$
freifunk_router_client_count_total{id="003192b11c58"} 2
freifunk_router_client_count_total{id="10feed2b1b36"} 1
freifunk_router_client_count_total{id="10feedeb80c0"} 1
freifunk_router_client_count_total{id="14cc20539834"} 1
```

patched metrics.go:
```go
# cat metrics.go 
package main

import (
        "log"
        "time"

        "github.com/prometheus/client_golang/prometheus"
        "github.com/xperimental/freifunk-exporter/info"
)

const (
        clientConnectionWifi24  = "wifi24"
        clientConnectionWifi5   = "wifi5"
        clientConnectionOther   = "other"
        clientConnectionUnknown = "unknown"
)

var (
        prefix = "freifunk_"

        collectorUpDesc = prometheus.NewDesc(
                prefix+"_collector_up",
                "Is set to 1 when the collector is able to get information.",
                []string{}, nil)
        collectorTimestampDesc = prometheus.NewDesc(
                prefix+"info_timestamp",
                "Contains the timestamp of the currently cached information.",
                []string{}, nil)
        metaDesc = prometheus.NewDesc(
                prefix+"router_meta",
                "Contains labels with metadata about a router. Value is fixed to 1.",
                []string{"id", "name", "hardware", "firmware", "community"}, nil)
        clientCountDesc = prometheus.NewDesc(
                prefix+"router_client_count_total",
                "Number of connected clients",
                []string{"id", "connection"}, nil)
        loadAvgDesc = prometheus.NewDesc(
                prefix+"router_load_avg_5m",
                "Contains the five minutes average load for a router.",
                []string{"id"}, nil)
        memoryUsageDesc = prometheus.NewDesc(
                prefix+"router_memory_usage_total",
                "Router memory usage as a fraction of the total.",
                []string{"id"}, nil)
        rootFsUsageDesc = prometheus.NewDesc(
                prefix+"router_rootfs_usage_total",
                "Router root filesystem usage as a fraction of the total.",
                []string{"id"}, nil)
)

type collector struct {
        sourceURL     string
        cacheDuration time.Duration
        lastInfo      *info.Meshinfo
        timestamp     time.Time
}

func newCollector(sourceURL string, cacheDuration time.Duration) *collector {
        return &collector{
                sourceURL:     sourceURL,
                cacheDuration: cacheDuration,
                lastInfo:      nil,
                timestamp:     time.Unix(0, 0),
        }
}

func (c *collector) Describe(ch chan<- *prometheus.Desc) {
        ch <- clientCountDesc
}

func (c *collector) Collect(ch chan<- prometheus.Metric) {
        now := time.Now()
        if now.Sub(c.timestamp) > c.cacheDuration {
                if err := c.updateCache(now); err != nil {
                        log.Printf("Error updating data: %s", err)
                }
        }

        c.sendCollectorMetrics(ch)
        if c.lastInfo == nil {
                return
        }

        c.updateNodes(ch, c.lastInfo.Nodes)
}

func (c *collector) updateCache(now time.Time) error {
        info, err := info.GetInfo(c.sourceURL)
        if err != nil {
                return err
        }

        c.timestamp = now
        c.lastInfo = info
        return nil
}

func (c *collector) sendCollectorMetrics(ch chan<- prometheus.Metric) {
        collectorUp := 0.0
        if c.lastInfo != nil {
                collectorUp = 1
        }

        sendMetric(ch, collectorUpDesc, collectorUp, []string{})
        sendMetric(ch, collectorTimestampDesc, float64(c.timestamp.Unix()), []string{})
}

func (c *collector) updateNodes(ch chan<- prometheus.Metric, nodes []info.Node) {
        for _, node := range nodes {
                if node.IsGateway {
                        // skip nodes that are not routers
                        continue
                }

                metaLabels := []string{node.ID, node.Hostname, node.Model, node.Firmware.Release, node.SiteCode}
                sendMetric(ch, metaDesc, 1.0, metaLabels)

                clientsUnknown := float64(node.Clients - node.ClientsWifi24 - node.ClientsWifi5 - node.ClientsOther)
                if clientsUnknown < 0 {
                        clientsUnknown = 0
                }
                sendMetric(ch, clientCountDesc, clientsUnknown, []string{node.ID, clientConnectionUnknown})

                sendMetric(ch, clientCountDesc, float64(node.ClientsWifi24), []string{node.ID, clientConnectionWifi24})
                sendMetric(ch, clientCountDesc, float64(node.ClientsWifi5), []string{node.ID, clientConnectionWifi5})
                sendMetric(ch, clientCountDesc, float64(node.ClientsOther), []string{node.ID, clientConnectionOther})

                idLabel := []string{node.ID}
                sendMetric(ch, loadAvgDesc, node.LoadAvg, idLabel)
                sendMetric(ch, rootFsUsageDesc, node.RootfsUsage, idLabel)

                if node.MemoryUsage > 0 {
                        sendMetric(ch, memoryUsageDesc, node.MemoryUsage, idLabel)
                }
        }
}

func sendMetric(ch chan<- prometheus.Metric, desc *prometheus.Desc, value float64, labels []string) {
        m, err := prometheus.NewConstMetric(desc, prometheus.GaugeValue, value, labels...)
        if err != nil {
                log.Printf("Error creating metric %q: %s", desc, err)
                return
        }

        ch <- m
}
```

**Comment by xperimental** [comment]
@jzielke84 Thanks for the update 🙂 
I forgot about this PR as well, no worries.

I'll try to give you feedback within the next week.

**Comment by tux-84** [comment]
Anything new on that issue?

**Comment by xperimental** [comment]
@jzielke84 Sorry, but no. I did not get to working on the personal projects the last Sundays, unfortunately. Maybe this Sunday...

**Comment by xperimental** [comment]
@jzielke84 I'm not sure, I get your question. When I run the version in the branch of this PR (current commit: `f0a5ab1dbb71c0f0f0b047ab9f66100fbf4ec427`) pointed to the datasource in your comment, I get back data containing clients listed by connection type, for example:

```
freifunk_router_client_count_total{connection="other",id="70a74180a4dd"} 0
freifunk_router_client_count_total{connection="unknown",id="70a74180a4dd"} 0
freifunk_router_client_count_total{connection="wifi24",id="70a74180a4dd"} 10
freifunk_router_client_count_total{connection="wifi5",id="70a74180a4dd"} 13
```

The `metrics.go` listed in your comment seems to be identical to the version in the branch except for being indented with spaces instead of tabs.

**Comment by tux-84** [comment]
Hm, maybe our datasource is different. Can you try parsing [this one](https://map.kbu.freifunk.net/data/ffkbub-V2/meshviewer.json)?

**Comment by xperimental** [comment]
@jzielke84 That is the datasource I tried it with as it's the one also mentioned in your previous comment.

One thing I noticed today while thinking about this again: the `connection` label does not just disappear depending on the datasource. It should at least show `connection="unknown"` if it can't discern the connection type from the data.

Have you built the binary you are using with the code from this branch? What's the command you use to build / run the exporter?

**Comment by tux-84** [comment]
> Have you built the binary you are using with the code from this branch? What's the command you use to build / run the exporter?

Damn, that's what I forgot. I just replaced the metrics.go and restarted the exporter service 🙈 Now everything is working as expected. Board can be seen [here](https://grafana.kbu.freifunk.net/).

**Comment by xperimental** [comment]
@jzielke84 Great to hear that it works :tada: 

I'll update the branch with the latest changes to get the CI running and also try it out on our own network (I'm pretty sure I already did this last year, but can not remember anymore) and if all that works fine, I'll merge it. Fine for you?

**Comment by tux-84** [comment]
> @jzielke84 Great to hear that it works 🎉
> 
> I'll merge it. Fine for you?

ok 👌

**Pull request merged**
